{
 "title": "Ethereum Prod Containers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Src",
   "type": "logs",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"prod_ethereum_src_container\"} |= ``"
    }
   ]
  },
  {
   "title": "UniswapV3LiquidityContainer",
   "type": "logs",
   "gridPos": { "h": 14, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"prod_ethereum_uniswap_v3_liquidity_container\"} |= ``"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "logs",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"prod_ethereum_swap_container\"} |= ``"
    }
   ]
  },
  {
   "title": "Token check",
   "type": "logs",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container=\"prod_ethereum_token_check_container\"} |= ``"
    }
   ]
  },
  {
   "title": "DB",
   "type": "logs",
   "gridPos": { "h": 14, "w": 8, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "{container=\"prod_ethereum_db_container\"} |= ``"
    }
   ]
  },
  {
   "title": "BoughtTokens",
   "type": "logs",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "{container=\"prod_ethereum_bought_token_check_container\"} |= ``"
    }
   ]
  }
 ]
}